_docs/installation.md
The introduction in the docs incorrectly implies that mrsk deploy will also install Docker and curl, which it doesn't. In order to make it as easy as possible to get started with MRSK, I think it's worth changing this to mrsk setup.
This PR brings the docs up to date with the readme of the [mrsked/mrsk repo](https://github.com/mrsked/mrsk).
See [here](https://github.com/mrsked/mrsk/issues/301) for the context discussion.
=> docs: change intro command to mrsk setup

_docs/commands.md
Two changes here:
- Separate out each example command in the first section into its own code block, instead of one large code block.
- Use `console` instead of `bash` for syntax highlighting for the CLI examples, which gets a better highlighting result for the combination of commands and their output.
Before:
After:
=> Improve readability of commands page examples

_docs/configuration.md
Adding short sentence describing "log_lines" setting for healthcheck (introduced by https://github.com/basecamp/kamal/pull/444 PR)
=> Describe "log_lines" Config for Healthcheck

_docs/installation.md
The alias provided in the documentation does not work on MacOS because ssh sharing requires a specific mounting point on MacOS.
I searched a long time before I succeeded in using Mrsk the first time I tried it.
I'd like to help future users to not loose time installing Kamal because of something not Kamal related.
=> Add a specific alias for MacOS on installation documentation

_docs/configuration.md
Documentation for healthcheck's `exposed_port` config param: https://github.com/basecamp/kamal/pull/443
=> Describe "exposed_port" Config for Healthcheck

_docs/commands.md, _docs/configuration.md
See https://github.com/basecamp/kamal/pull/438
=> Docs for env push

_docs/configuration.md
See https://github.com/basecamp/kamal/pull/437
=> Configuring the run directory

_docs/installation.md
Given `.bashrc` / `.zshrc` files are normally stored in the home fodler (`~`) folder, the `$PWD` variable becomes `~` even if the alias is called from another folder. Wrapping the alias command in single quotes avoids this premature expansion of the variable.
=> Updated Docker alias command

_docs/installation.md
- Adds a Linux variant for the `kamal` alias. The alias changed in https://github.com/basecamp/kamal-site/pull/25 and this current version doesn't seem to work on Linux (I'm on Ubuntu 20.04).
=> Add Linux alias command

_docs/configuration.md
Running `kamal accessory start mysql` with a new accessory will return an error:
```
docker stderr: Error response from daemon: No such container: hey-db
Error: failed to start containers: hey-db
```
Instead we should have people boot their container first via `kamal accessory boot mysql`w.
=> Accessories need to be booted before they can be started

_docs/configuration.md
```yml
job:
hosts:
- 123.123.123.123
cmd: bundle exec sidekiq
options:
cap-add: true
cpu-count: 2
```
raises:
```docker: Error response from daemon: invalid CapAdd: unknown capability: "CAP_--CPU-COUNT"```
We should use `cpus`
```yml
job:
hosts:
- 123.123.123.123
cmd: bundle exec sidekiq
options:
cpus: 4
```
=> updated options cpu counts

_docs/configuration.md
This took a bit of figuring out but now my first Kamal deployment is complete 🎉 
The described way of using GCP Artifact Registry should be familiar to anyone who used GCP IAM before but there are a few twists that are not as intuitive. I hope this is not too verbose compared to the concise AWS section!
Also, searching the Discord for answers, I stumbled upon the recommendation to use `kamal registry login`, I feel it should be mentioned in the configuration doc too.
=> Add a GCP Artifact Registry configuration example

_docs/configuration.md
After struggling for a bit with getting Kamal to build for amd64 on both Intel and ARM Macs, I figured out how to configure the builder. Adding a section about it as it seems to be something other's try to do too. 
Thread about it [here](https://github.com/basecamp/kamal/discussions/549)
=> Documentation section about using local builder for single-arch

_docs/configuration.md
The examples in the current docs can result in a publicly-exposed accessories, e.g. a public redis instance, not protected by a password.
I added a short note on how you can avoid that either by setting a password/firewall or explicitly declaring the IP the service listens on.
=> Add note on accessories and security

_docs/configuration.md
Dotenv only captures the first line unless there are double quotes and then it still preserves the newlines since 3.0 https://github.com/bkeepers/dotenv?tab=readme-ov-file#multi-line-values
=> Remove newline in GCP config

_data/github.yml
Not sure if there's an automated way of doing this.
But here's a PR to bump the version to the latest tagged version of Kamal.
=> Bump kamal version in header to 1.4.0

docs/hooks/index.md
=> Keep links relative to index to stay in /hooks/ namespace

docs/commands/server.md
Fixing typo on docs (https://kamal-deploy.org/docs/commands/server/)
=> docs(command-server): fix typo `if` to `it`

docs/configuration/environment-variables.md
The `KAMAL_VERSION` environment variable [is made available within the container](https://github.com/basecamp/kamal/blob/v1.5.2/lib/kamal/commands/app.rb#L20), but this was not documented, with `KAMAL_VERSION` only being mentioned [in the context of the hooks' environment variables](https://github.com/basecamp/kamal-site/blob/f66341197fa6329057f7836f7ba3240d6424e115/docs/hooks/hooks-overview.md?plain=1#L20).
=> Mention `KAMAL_VERSION` container environment variable

docs/hooks/hooks-overview.md
My team was trying to use hooks with a `.sh` extension. Adding this clarification might help other users avoid similar problems.
=> Update Hooks Documentation to Include Filename Requirement

docs/configuration/index.md
While on `Installation` (https://kamal-deploy.org/docs/installation/) page, when clicking the `Next (Configuration)` link, it should should the `Configuration overview` page. But, instead, it shows a not found page.
This PR adds an index file to redirect to the "Configuration Overview" page.
=> Fix page not found when visiting configuration index

docs/commands/traefik.md
Seems like a few words got lost in the sentence regarding rebooting traefik. Fixed that.
=> Fix a typo in traefik.md

docs/commands/build.md
This mentions that Kamal will, by default, only build code committed to git. And also how to override this. This closes https://github.com/basecamp/kamal-site/issues/96.
=> Add a note in `kamal build` about `#git_archive?`

docs/hooks/hooks-overview.md
Update site to mention ENV['KAMAL_SERVICE'] is now available within the hooks.
Related PR: https://github.com/basecamp/kamal/pull/868
=> Mention KAMAL_SERVICE in hooks overview

docs/upgrading/secrets-changes.md
The link in the following section is broken
https://kamal-deploy.org/docs/upgrading/secrets-changes/#interpolating-secrets
=> Fix broken link in upgrade guide

docs/upgrading/secrets-changes.md
Minor change, just moving the dots out of the code clock
Before
After
=> Better readability & avoid copy-paste problems

docs/configuration/environment-variables.md, docs/upgrading/secrets-changes.md
Destination-specific secret files are actually looked up with a dot prefix (e.g., `secrets.production`) instead of a hyphen prefix (e.g., `secrets-production`, as currently pointed out in the docs), according to https://github.com/basecamp/kamal/blob/8c32e6af07356031ffbad2e8eb60169904bc5e52/lib/kamal/secrets.rb#L10
=> Update docs with correct secret file paths for destination-specific secrets

docs/commands/proxy.md, docs/configuration/environment-variables.md, docs/upgrading/configuration-changes.md, docs/upgrading/secrets-changes.md, v1/docs/configuration/environment-variables.md
Corrects the following broken links:
```
../hooks/pre-proxy-reboot > ../../hooks/pre-proxy-reboot
../hooks/post-proxy-reboot > ../../hooks/post-proxy-reboot
../commands/secrets > ../../commands/secrets
../configuration/builders > ../../configuration/builders
../configuration/environment-variables[...] > ../../configuration/environment-variables[...]
/docs/commands/envify/ > ../../commands/envify/
```
=> Corrects broken links on the site

docs/configuration/proxy.md
Following the [change in kamal-proxy](https://github.com/basecamp/kamal-proxy/pull/17) and [a corresponding change in kamal](https://github.com/basecamp/kamal/pull/969), this MR adds documentation for the configuration option to load custom SSL certificate and the corresponding private key from disk:
=> Documentation for custom SSL certificates

docs/configuration/overview.md
The support for configuring the `run_directory` has been dropped in the switch from Traefik to kamal-proxy, with this commit: https://github.com/basecamp/kamal/pull/940/commits/27a7b339a6fadda1614fd2a8c3903d3c1d54038c
=> Remove `run_directory` documentation

assets/css/style-v2.scss, docs/configuration/proxy.md
This PR adds an example of specifying multiple hosts within the proxy host field.
ref: https://github.com/basecamp/kamal-proxy/issues/14
=> Adds multiple hosts documentation

docs/upgrading/configuration-changes.md
Several developers reported that they didn't expect kamal-proxy to forward traffic to the container port 80 by default. The last example is here: https://github.com/basecamp/kamal/issues/987.
I added a paragraph about this.
=> Mentioned changing app_port setting during upgrade

docs/configuration/proxy.md
Reverts basecamp/kamal-site#100, as this change has not landed yet.
=> Revert "Documentation for custom SSL certificates"

docs/upgrading/overview.md
The new app listening port setting is a bit difficult to find, it'd be great to mention the change on the upgrade overview instructions. Seeing quite a few discussions on Discord about their app failing to boot when upgrading and this is one of the most common issues coming up.
=> Mention new container port on upgrade overview

docs/configuration/accessories.md
So it's now clickable in the docs online
=> Using markdown link in accessories docs

docs/configuration/docker-registry.md
I made this PR as result of [discussion](https://github.com/basecamp/kamal/discussions/1128).
Docker hub by default creates publicly available docker images and some uses may accidentally make their images public.
=> Add info about default public images at docker hub

docs/configuration/aliases.md
Got tripped up on this for a minute, and realized that `-r` is for roles, and `--reuse` has no short flag
=> Fix wrong flag used in aliases docs for container reuse

docs/search/index.md
Fixes: https://github.com/basecamp/kamal/issues/1176
---
Using `strip_newlines` formatted `content` into (notice the missing whitespaces):
```
"Kamal 2: Configuration changesBuilderThe builder configuration has been simplified.ArchYou must specify the architecture(s) you are building for:# single archbuilder:  arch: amd64# multi archbuilder:  arch:    - amd64    - arm64Remote buildersSet the remote directly with the remote option. By default, it will only be used if the arch you are building doesn’t match the local machine:builder:  arch: amd64  remote: ssh://docker@docker-builderYou can force Kamal to only use the remote builder, by setting local: false:builder:  arch: amd64  local: false  remote: ssh://docker@docker-builderDriverKamal will now always use the Docker container (link) …
```
=> Search: Fix whitespaces

docs/upgrading/proxy-changes.md
Fixed a typo naming Traefik's EntryPoint as an Endpoint.
The correct naming is an EntryPoint: https://doc.traefik.io/traefik/routing/entrypoints/.
=> Fixed type in naming Traefik's EntryPoint as an Endpoint

docs/configuration/cron.md
Change the example to copy environment variables when installing crontab, it was a source of headaches for me because cron does not give any feedback about it.
=> Update cron docs

docs/configuration/proxy.md
This is especially important in the case you're putting your Rails app behind Cloudflare, and are using the `cloudflare-rails` gem to get the real user `request.remote_ip`. Without this option, gems like `cloudflare-rails` will fail to set the right headers and infer the right request IP as discussed in modosc/cloudflare-rails#165
=> Add a small note that enabling `ssl: true` makes `kamal-proxy` stop forwarding headers unless `forward_headers` is also set to `true`

docs/commands/secrets.md
Documentation for [feat: add secrets adapter for aws secrets manager](https://github.com/basecamp/kamal/pull/1141)
=> documentation for aws secrets manager

_data/docs.yml, docs/configuration/anchors.md, docs/configuration/overview.md
I was in the process of upgrading to Kamal 2 and needed to utilize the YML anchors functionality for a shared healthcheck across a handful of worker roles. I found the docs within the actual Kamal gem but thought it'd be helpful to have a full example on the site as well.
There is an "extensions" section on the configuration overview section but this makes me think that we're extending Kamal with additional functionality, we also mention YAML anchors here:
YML anchors/aliases are fairly common, it's also part of the YML spec. Should we just rename to `anchors` and reserve `extensions` for some possible extension/plugin system in the future? I can tweak the configuration overview section to call them anchors if so or I can just rename the anchors page to extensions.
=> Add a full example of using yml anchors

docs/commands/build.md
Documentation for feature introduced in https://github.com/basecamp/kamal/pull/1357
=> Add the "build dev" command to "build.md"

docs/commands/secrets.md
This PR adds documentation for using the GCP Secret Manager adapter (added in https://github.com/basecamp/kamal/pull/1236)
-  Created a new section in the documentation for GCP Secret Manager.
-  Added detailed examples of fetching secrets with different configurations:
- Using default credentials and project.
- Fetching secrets from specific projects.
- Handling multiple projects.
- Fetching specific versions of secrets.
- Using impersonation for access control.
=> Add gcp secrets adapter docs

_sass/base/_root.scss, _sass/base/_rouge.scss, _sass/modules/_footer.scss, _sass/modules/_nav.scss, _sass/modules/_page.scss, _sass/modules/_video.scss, index.html
this adds a dark theme.
<table>
<tr>
<td valign="top"> <img src="https://github.com/user-attachments/assets/287254c7-58db-48da-8bbc-6dd123b86a70"> </td>
<td valign="top"> <img src="https://github.com/user-attachments/assets/cc4d04e2-3969-48d8-b677-e57cd4d9f0b4"> </td>
<td valign="top"> <img src="https://github.com/user-attachments/assets/c3943eaf-739e-46d1-920b-18693374035a"> </td>
</tr>
</table>
=> prevent eye-bleed

docs/commands/secrets.md
Documentation for https://github.com/basecamp/kamal/pull/1422
=> docs: add Passbolt adapter usage

docs/configuration/builder-examples.md
For buildpacks addition PR https://github.com/basecamp/kamal/pull/916
=> Add a builder example section about buildpacks
