assets/videos/introducing-mrsk.srt, index.html
I used https://github.com/ggerganov/whisper.cpp to generate an SRT subtitle file for the MRSK introduction video. I tweaked some spellings and then embedded the SRT into the original video file. I opted to also include the SRT file as an asset as well as preserve the original video file in git. In reality, both are probably not needed, but I'll let the MRSK team decide. 😄
=> Add SRT subtitles to intro video

_docs/configuration.md
I couldn't see any documentation on how directories work so I added it here. I think I've understood it correctly?
=> adds guidance on using directories

_docs/configuration.md
Change introduced in https://github.com/basecamp/kamal/pull/368
=> Document "publish: false" option for Traefik.

_docs/configuration.md
See https://github.com/basecamp/kamal/pull/449
=> Asset path configuration

_docs/configuration.md
See https://github.com/basecamp/kamal/pull/439
=> Zero downtime with cordfile

_docs/commands.md
Some commands actually correspond to the quiet version of the command.
=> Update commands.md with quiet flag when required

_docs/configuration.md
Follow up to https://github.com/basecamp/kamal/pull/508
=> Add SSH port documentation

_docs/hooks.md
This hook has just been merged into Kamal, so adding the documentation.
https://github.com/basecamp/kamal/pull/585
=> Add docker-setup hook documentation

docs/hooks/hooks-overview.md
Fixes the hooks link in the page https://kamal-deploy.org/docs/hooks/hooks-overview/
=> Fix hook links

_data/docs.yml, _data/github.yml, docs/commands/healthcheck.md, docs/commands/help.md, docs/commands/view-all-commands.md, docs/configuration/healthchecks.md
- Remove healthcheck command references, and references to separate healthcheck step
- Update version tag
=> Update docs for Kamal 1.6.0

_sass/base/_fonts.scss, _sass/base/_root.scss, _sass/modules/_header.scss, index.html
Solved problems:
- (**Accessibility**) Buttons do not have an accessible name
- (**Accessibility**) Background and foreground colors do not have a sufficient contrast ratio.
- (**Accessibility**) Heading elements are not in a sequentially-descending order
- (**Performance**) Ensure text remains visible during webfont load
=> Accessibility and Performance improvements

_data/docs.yml, docs/configuration/cron.md
Unintentionally removed in #79.
=> Restore cron docs

_data/github.yml, docs/commands/version.md, docs/configuration/configuration-overview.md
Add info on extensions, update version.
=> Update docs for Kamal 1.8.1

docs/configuration/environment-variables.md
Fixes a broken link pointing to the secrets command.
=> Fixing secret helpers link

docs/upgrading/configuration-changes.md
discussion: https://discord.com/channels/1084848369073131531/1084848372667654248/1289001901504860211
=> Add side note for a change of default proxy port

docs/commands/secrets.md
Similar to https://github.com/basecamp/kamal-site/pull/123 for LastPass and Bitwarden.
=> Add install instruction for LastPass and Bitwarden

docs/installation/index.md
A simple addition to docs for new Mac users
=> Update installation docs

docs/configuration/aliases.md
`bin/rails` to trigger a command.
=> rails --> bin/rails command example in aliases

docs/commands/proxy.md
For https://github.com/basecamp/kamal/issues/1274
=> Mention docker-options for proxy boot config

docs/installation/dockerized.md, docs/installation/index.md
Running Kamal via Docker has a bunch of gotchas, so note them.
=> Warnings about Kamal in Docker

docs/commands/proxy.md
See https://github.com/basecamp/kamal/issues/1311#issuecomment-2583165326
=> Less confusing description for kamal proxy boot_config

Gemfile.lock, _data/github.yml, _data/nav.yml, docs/commands/accessory.md, docs/commands/app.md, docs/commands/build.md, docs/commands/help.md, docs/commands/proxy.md, docs/commands/prune.md, docs/commands/registry.md, docs/commands/version.md, docs/commands/view-all-commands.md, docs/configuration/accessories.md, docs/configuration/environment-variables.md, docs/configuration/overview.md, docs/configuration/proxy.md
Updates for version 2.6.0 of Kamal
=> Kamal 2.6 updates
